// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';


function defaultUnrecognizedRouteHandler(_, _$1) {
  return this.navigate("/");
}

function defaultNavigateState() {
  return ({});
}

export {
  defaultUnrecognizedRouteHandler ,
  defaultNavigateState            ,
  
}
/* No side effect */
