// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

import * as $$Array    from "bs-platform/lib/es6/array.js";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as Js_boolean from "bs-platform/lib/es6/js_boolean.js";

function hasLeadingSlash(path) {
  return Js_boolean.to_js_boolean(+path.startsWith("/"));
}

function ensureLeadingSlash(path) {
  var match = +hasLeadingSlash(path);
  if (match !== 0) {
    return path;
  } else {
    return "/" + path;
  }
}

function hasTrailingSlash(path) {
  return Js_boolean.to_js_boolean(+path.endsWith("/"));
}

function ensureTrailingSlash(path) {
  var match = +hasTrailingSlash(path);
  if (match !== 0) {
    return path;
  } else {
    return path + "/";
  }
}

function pathFromHash(url) {
  var match = $$Array.to_list(url.split("#"));
  var path;
  if (match) {
    var match$1 = match[1];
    path = match$1 && !match$1[1] ? match$1[0] : "/";
  } else {
    path = "/";
  }
  return ensureLeadingSlash(ensureTrailingSlash(path));
}

function noop() {
  return 1;
}

function trimQueryParams(path) {
  return Caml_array.caml_array_get(path.split("?"), 0);
}

export {
  hasLeadingSlash     ,
  ensureLeadingSlash  ,
  hasTrailingSlash    ,
  ensureTrailingSlash ,
  pathFromHash        ,
  noop                ,
  trimQueryParams     ,
  
}
/* No side effect */
